version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./symfony/:/var/www/symfony/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: crm_system_nginx
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: dev
    volumes:
      - ./symfony/:/var/www/symfony/
    container_name: crm_system_php
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test_project
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: crm_system_mysql